### ISSUE TITLE
Kubeconform schemas need updating?

### ISSUE THREAD

**Issue by sengi** [alphagov/govuk-helm-charts#1597]
We have [kubeconform schemas](https://github.com/alphagov/govuk-helm-charts/tree/main/schemas) in-tree for the CRDs that we use (for those that kubeconform doesn't already know about).

We haven't updated them in a while so we might start tripping over validation errors where schemas lack fields etc. from newer versions of CRDs.

**Comment by samsimpson1** [comment]
We could point kubeconform to this repo: https://github.com/datreeio/CRDs-catalog

The CRDs there are updated pretty often, and they seem to have all of the CRDs we're using
